### ISSUE TITLE
Slightly confusing message when string key is mixed up for atom key

### ISSUE THREAD

**Issue by axelson** [mtrudel/machete#40]
This assertion (and the reverse) `assert %{foo: "bar"} ~> %{"foo" => "bar"}` results in an unclear message:

```
     Assertion with ~> failed

     Mismatches:

       1) .foo: Unexpected key
       2) .foo: Missing key
```
It's confusing because it looks like the same key is missing, but also unexpected. It might make sense to instead have a custom message in this case, maybe something like `.foo: The atom :foo was received, but the string "foo" was expected`

**Comment by axelson** [comment]
Yeah I'd like to, but no promises on when I'll get around to it. And thank you for the link to that snippet of code to get started.

**Comment by mtrudel** [comment]
No hurry on my end!
